# Este archivo no debe editarse manualmente.
# Indica que las migraciones de Prisma están configuradas para PostgreSQL.
# Su función es mantener la consistencia entre el esquema de la base de datos
# y las migraciones generadas por Prisma en todos los entornos del proyecto.

provider = "postgresql"